Bump min openstacksdk version for os_network/{port_security_enabled,mtu}
To make use of the port_security_enabled [a] and mtu [b] parameters,
[c] and [d] need to be present in the openstacksdk or the os_network
module with return an error like:

TypeError: create_network() got an unexpected keyword argument 'port_security_enabled'

or:

TypeError: create_network() got an unexpected keyword argument 'mtu'

To handle this, we fail the module if one of the arguments are used
and the minimum openstacksdk version for that argument is not met.

[a] https://github.com/ansible/ansible/commit/eaf238b033a0504c48440cf85982a2b89851059d
[b] https://github.com/ansible/ansible/commit/c6a8e99d34eeacd84b097bb0bd2ba9a0d7fb230d
[c] https://github.com/openstack/openstacksdk/commit/8eb788af07ed88166db7b8a58ce1fecacd7a29b1
[d] https://github.com/openstack/openstacksdk/commit/a1fc820a2f3669f64d222506c17be99c4d6be7b7

Fixes: https://github.com/ansible/ansible/issues/62062
Change-Id: I2b80dc721a08bbdb530af3705ae99cf1b579d9f0